default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root  
  password: 123456 
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: marketplace_api_development

test:
  <<: *default
  database: marketplace_api_test

production:
  <<: *default
  database: marketplace_api_production
  username: marketplace_api
  password: <%= ENV["MARKETPLACE_API_DATABASE_PASSWORD"] %>  # A senha deve ser configurada como uma variável de ambiente segura
